
rule all:
    input: "renamed.fa", "renamed_dig.fa"


rule rename:
    input:
        "seq.fa"
    output:
        "renamed.fa"
    params:
        sample = "XY123",
        host = "bat",
        location = "Estonia",
        collection_date = "2021-02-15",
        hexdigest = False,
    wrapper:
        "file:../wrapper.py"

rule rename_dig:
    input:
        "seq.fa"
    output:
        "renamed_dig.fa"
    params:
        sample = "XY123",
        host = "bat",
        location = "Estonia",
        collection_date = "2021-02-15",
        hexdigest = True
    wrapper:
        "file:../wrapper.py"
