rule genome_consensus:
    input:
        reads=["unmaphost.fq", "unmaphost.fq"],
        ref = "NC_045512.fa",
        vcf = "filtered.vcf"
    output:
        vcfgz="filtered.vcf.gz",
        consensus="consensus.fa",
        sam="consensusmap.sam",
        consensus_masked="consensus_masked.fa",
        bed="refgenome.bed"
    log:
        "test.log"
    params:
        mask = 20,
        extra="-Xmx3200m fast"
    wrapper:
        "file:../wrapper.py"
