rule genome_consensus:
    input:
        alignment="refgenome.bam",
        ref = "NC_045512.fa",
        vcf = "filtered.vcf"
    output:
        "results/consensus.fa",
    log:
        "log/test.log"
    params:
        mask = 5,
        mapping_quality = 20,
    wrapper:
        "file:../wrapper.py"
