
rule bbwrap:
    input:
        in1 = "sample1.fq.gz",
        in2 = "sample2.fq.gz",
        ref = "phiX174_ill.ref.fa.gz"
    output:
        outm = "mapped.sam",
        bam = "mapped_sorted.bam"
    params:
        extra = "nodisk bamscript=bs.sh",
        Xmx = 1000
    log:
        "align2.log"
    resources:
        runtime = 10,
        mem_mb = 1000
    wrapper:
        "file:../wrapper.py"
#        "https://raw.githubusercontent.com/avilab/virome-wrappers/feature/bbwrap/bbmap/bbwrap"
