
import os
# Path to reference genomes
HOST_GENOME = os.environ["REF_GENOME_HUMAN_MASKED"]
RRNA_DB = os.environ["SILVA"]

fastq_screen_config = {
  "database": {
    "human": HOST_GENOME,
    "SILVA_138_SSURef_NR99": RRNA_DB
  }
}

rule fastq_screen:
    input:
        "sample.fq.gz"
    output:
        txt = "qc/fastq_screen.txt",
        png = "qc/fastq_screen.png"
    params:
        fastq_screen_config=fastq_screen_config,
        subset = 100000
    log:
        "fastq_screen.log"
    threads: 4
    wrapper:
        "file:../wrapper.py"
