
rule preprocess:
    input:
        "sample1.fq.gz", "sample2.fq.gz"
    output:
        adapters = "adapters.fa",
        merged = "merged.fq",
        unmerged = "unmerged.fq",
        reads = "reads.fq",
        trimmed = "trimmed.fq",
        sampled = "sampled.fq"
    params:
        bbduk = "qtrim=r trimq=10 maq=10 minlen=100"
    wrapper:
        "file:../wrapper.py"
