
rule bbwrap:
    input:
        in1 = "sample1.fq.gz",
        in2 = "sample2.fq.gz",
        ref = "phiX174_ill.ref.fa.gz"
    output:
        outm = "mapped.sam"
    params:
        extra = "-Xmx1g nodisk bamscript=bs.sh"
    log:
        "align2.log"
    wrapper:
        "https://raw.githubusercontent.com/avilab/virome-wrappers/feature/bbwrap/bbmap/bbwrap"
